name: Sync

on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Sync to Gitee
            uses: wearerequired/git-mirror-action@v1
            env:
                # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
                SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
            with:
                # 注意替换为你的 GitHub 源仓库地址
                source-repo: "git@github.com:xiaoqingdu/xiaoqingdu.github.io.git"
                # 注意替换为你的 Gitee 目标仓库地址
                destination-repo: "git@gitee.com:xiaoqingdu/xiaoqingdu.git"

          - name: Build Gitee Pages
            uses: xiaoqingdu/gitee-pages-action@v1.1.4
            with:
                # 注意替换为你的 Gitee 用户名
                gitee-username: xiaoqingdu
                # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
                gitee-password: ${{ secrets.GITEE_PASSWORD }}
                # 注意替换为你的 Gitee 仓库
                gitee-repo: xiaoqingdu/xiaoqingdu
